Remove --color=always from diff

diff --git a/.test/task1/validate b/.test/task1/validate
--- a/.test/task1/validate
+++ b/.test/task1/validate
@@ -48,8 +48,8 @@ function test_solution() {
     echo "$ACTUAL"
     fail
   fi
-  diff --color=always -U 1000 <(echo "") <(echo "$ACTUAL") || fail
-  diff --color=always -r -U 1000 "$EXPECTED" "$ARCHIVE_NAME.unpacked/root" || fail
+  diff -U 1000 <(echo "") <(echo "$ACTUAL") || fail
+  diff -r -U 1000 "$EXPECTED" "$ARCHIVE_NAME.unpacked/root" || fail
 }
 
 
diff --git a/.test/task3/validate b/.test/task3/validate
--- a/.test/task3/validate
+++ b/.test/task3/validate
@@ -36,7 +36,7 @@ function test_solution() {
     echo "$ACTUAL"
     fail "$@"
   fi
-  diff --color=always -U 1000 <(echo "$EXPECTED") <(ls -A -1) || fail "$@"
+  diff -U 1000 <(echo "$EXPECTED") <(ls -A -1) || fail "$@"
 }
 
 
